// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      // This app uses anonymous/public data access only. Avoid auth-session
      // persistence/refresh to prevent gotrue lock contention in long sessions.
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

declare global {
  // preserve the client across HMR in dev to avoid multiple instances
  // eslint-disable-next-line no-var
  var __supabase_client__: ReturnType<typeof createSupabaseClient> | undefined;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined =
  typeof globalThis !== "undefined" && (globalThis as any).__supabase_client__
    ? (globalThis as any).__supabase_client__
    : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      _supabase = createSupabaseClient();
      if (typeof globalThis !== "undefined") (globalThis as any).__supabase_client__ = _supabase;
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});
