// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

/**
 * Safely read an env var across all runtimes:
 *  1. Vite build-time replacement (VITE_* prefix)   — works everywhere
 *  2. import.meta.env (Vite SSR)
 *  3. globalThis.__cf_env__ — Cloudflare Workers env bindings injected by the adapter
 *  4. process.env (Node.js dev server) — guarded with try/catch because
 *     `process` is not defined in the Cloudflare Workers runtime.
 */
function getEnv(viteKey: string, nodeKey: string): string | undefined {
  // 1. Vite build-time replacement — always preferred
  const viteVal = (import.meta.env as Record<string, string | undefined>)[viteKey];
  if (viteVal) return viteVal;

  // 2. Cloudflare Workers env object injected into globalThis by the CF adapter
  const cfEnv = (globalThis as Record<string, unknown>).__cf_env__;
  if (cfEnv && typeof cfEnv === "object" && nodeKey in cfEnv) {
    return (cfEnv as Record<string, string>)[nodeKey];
  }

  // 3. Node.js process.env (dev server) — wrapped so it doesn't crash CF Workers
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const val = (globalThis as any).process?.env?.[nodeKey];
    if (val) return val;
  } catch {
    // process is not defined on Cloudflare Workers — silently ignore
  }

  return undefined;
}

function createSupabaseClient() {
  const SUPABASE_URL = getEnv("VITE_SUPABASE_URL", "SUPABASE_URL");
  const SUPABASE_PUBLISHABLE_KEY = getEnv(
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_PUBLISHABLE_KEY",
  );

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Missing Supabase environment variables. " +
        "Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file, " +
        "and add them as Cloudflare secrets via: wrangler secret put SUPABASE_URL",
    );
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      // This app uses anonymous/public data access only. Avoid auth-session
      // persistence/refresh to prevent gotrue lock contention in long sessions.
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

declare global {
  // preserve the client across HMR in dev to avoid multiple instances
  // eslint-disable-next-line no-var
  var __supabase_client__: ReturnType<typeof createSupabaseClient> | undefined;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined =
  typeof globalThis !== "undefined" && (globalThis as any).__supabase_client__
    ? (globalThis as any).__supabase_client__
    : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) {
      _supabase = createSupabaseClient();
      if (typeof globalThis !== "undefined") (globalThis as any).__supabase_client__ = _supabase;
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});
